version: '2'
services:
  node1:
    environment:
      - NAME=1
      - HOST=0.0.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    volumes:
    - ./:/naivecoin
  node2:
    environment:      
      - HOST=0.0.0.0
      - NAME=2
      - PEERS=http://node1:3001      
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    volumes:
    - ./:/naivecoin
    links:
      - node1:node1
  node3:
    environment:
      - HOST=0.0.0.0
      - NAME=3
      - PEERS=http://node2:3001      
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    volumes:
    - ./:/naivecoin
    links:
      - node2:node2
